apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "another-test-usernamepass"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
# job/folder scope - optional - individual items must begin and end with '/'
    jenkins.io/credentials-item-group: ["/job/thisIsJobA/", "/job/thisIsJobB/job/nestedJob/"]
type: Opaque
stringData:
  username: myUsername
  password: 'Pa$$word'
